# Generated by Django 5.0.6 on 2024-06-24 08:43

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iccSPA', '0002_boleta_detallecompra'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detallecompra',
            name='boleta',
        ),
        migrations.AddField(
            model_name='detallecompra',
            name='total',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='BoletaCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('estado', models.CharField(default='recibido', max_length=20)),
                ('detalles', models.ManyToManyField(to='iccSPA.detallecompra')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Boleta',
        ),
    ]
