# Generated by Django 5.0.6 on 2024-06-24 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iccSPA', '0003_remove_detallecompra_boleta_detallecompra_total_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boletacompra',
            name='detalles',
            field=models.ManyToManyField(related_name='boletas', to='iccSPA.detallecompra'),
        ),
    ]
